extensions:
    pim-menu-klizer-aws:
        module: pim/menu/item
        parent: pim-menu
        position: 200  # Adjust the position as needed
        targetZone: mainMenu
        config:
            title: klizer_aws.menu.title  # This will be your translation key for the title
            iconModifier: AssetCollectionIcon
            icon: AssetCollectionIcon
            to: klizer_aws  # This will point to the route /klizer/hello

