extensions:
    klizerawss3-configuration-form:
        module: klizerawss3/js/form/configuration/index
        targetZone: content
        routes:
            - klizer_aws_configuration
            
    klizer-aws-main-tab:
        module: klizerawss3/form/configuration/index
        targetZone: content
        config:
            tabCode: klizeraws

    klizer-aws-tab-documentation:
        module: klizerawss3/js/form/configuration/tab/documentation
        parent: klizerawss3-configuration-form
        targetZone: content
        position: 100

    klizer-aws-tab-credentials:
        module: klizerawss3/js/form/configuration/tab/credentials
        parent: klizerawss3-configuration-form
        targetZone: content
        position: 110

    klizer-aws-tab-support:
        module: klizerawss3/js/form/configuration/tab/support
        parent: klizerawss3-configuration-form
        targetZone: content
        position: 120

    pim-menu-klizeraws:
        module: pim/menu/tab
        parent: pim-menu
        targetZone: mainMenu
        config:
            title: Klizer AWS
            to: klizer_aws_configuration
            icon: cloud
            iconModifier: icon-klizeraws

